apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bs-test-service
  annotations:
    github.com/project-slug: hoyon/bs-test-service
spec:
  type: service
  lifecycle: experimental
  owner: pumped-squids

